-- Add up migration script here
ALTER TABLE candidate_guide_races
ADD COLUMN were_candidates_emailed BOOLEAN DEFAULT FALSE,
ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_updated_at
BEFORE UPDATE
ON candidate_guide_races
FOR EACH ROW
EXECUTE PROCEDURE SET_UPDATED_AT();
